apiVersion: v1
entries:
  cac-system:
  - apiVersion: v2
    appVersion: 1.16.0
    created: "2025-04-30T15:58:38.587018+08:00"
    dependencies:
    - name: metallb
      repository: https://metallb.github.io/metallb
      version: 0.13.10
    - alias: cert-manager
      condition: cert-manager.enabled
      name: cert-manager
      repository: https://charts.jetstack.io
      version: v1.12.0
    description: A Helm chart for Kubernetes
    digest: 9430596f57aaba2fd8f3a2bd0d49ee471f1d164421bfa406f567abda236232e8
    name: cac-system
    type: application
    urls:
    - https://huangchengwu.github.io/helm-chart/chart/cac-system-0.1.0.tgz
    version: 0.1.0
  influxdb:
  - apiVersion: v2
    appVersion: 1.16.0
    created: "2025-04-30T15:58:38.587285+08:00"
    description: A Helm chart for Kubernetes
    digest: 3b53adfebf9e49c51960b9424e066db59485391ddb97e9339d0aefa0d2314900
    name: influxdb
    type: application
    urls:
    - https://huangchengwu.github.io/helm-chart/chart/influxdb-0.1.0.tgz
    version: 0.1.0
  jenkins:
  - apiVersion: v2
    appVersion: 1.16.0
    created: "2025-04-30T15:58:38.587638+08:00"
    description: A Helm chart for Kubernetes
    digest: 509603232d3cec8415b479a66ac086bed9184c64123d504b3ea176de73608906
    name: jenkins
    type: application
    urls:
    - https://huangchengwu.github.io/helm-chart/chart/jenkins-0.1.0.tgz
    version: 0.1.0
  mariadb:
  - apiVersion: v2
    appVersion: 1.16.0
    created: "2025-04-30T15:58:38.587876+08:00"
    description: A Helm chart for Kubernetes
    digest: 02a7ccdd819364bcb338febd8582dbe82e8e89f966a235f2d658e5c24fd4336b
    name: mariadb
    type: application
    urls:
    - https://huangchengwu.github.io/helm-chart/chart/mariadb-0.1.0.tgz
    version: 0.1.0
  mariadb-galera:
  - annotations:
      category: Database
      images: |
        - name: mariadb-galera
          image: docker.io/bitnami/mariadb-galera:11.3.2-debian-12-r3
        - name: mysqld-exporter
          image: docker.io/bitnami/mysqld-exporter:0.15.1-debian-12-r16
      licenses: Apache-2.0
    apiVersion: v2
    appVersion: 11.3.2
    created: "2025-04-30T15:58:38.590602+08:00"
    dependencies:
    - name: common
      repository: oci://registry-1.docker.io/bitnamicharts
      tags:
      - bitnami-common
      version: 2.x.x
    description: MariaDB Galera is a multi-primary database cluster solution for synchronous
      replication and high availability.
    digest: 5afe60ec5fb8b323b5ae99daa2561df04e383884986116c37da40c333107433f
    home: https://bitnami.com
    icon: https://bitnami.com/assets/stacks/mariadb-galera/img/mariadb-galera-stack-220x234.png
    keywords:
    - mariadb
    - mysql
    - database
    - sql
    - prometheus
    - galera
    maintainers:
    - name: Broadcom, Inc. All Rights Reserved.
      url: https://github.com/bitnami/charts
    name: mariadb-galera
    sources:
    - https://github.com/bitnami/charts/tree/main/bitnami/mariadb-galera
    urls:
    - https://huangchengwu.github.io/helm-chart/chart/mariadb-galera-13.2.1.tgz
    version: 13.2.1
  mysql:
  - apiVersion: v2
    appVersion: 1.16.0
    created: "2025-04-30T15:58:38.590903+08:00"
    description: A Helm chart for Kubernetes
    digest: 12d194f77a0097f545583f0f0cbf837d578a18041f242c8dd694b918df046ea3
    name: mysql
    type: application
    urls:
    - https://huangchengwu.github.io/helm-chart/chart/mysql-0.1.0.tgz
    version: 0.1.0
  nexus3:
  - apiVersion: v2
    appVersion: 1.16.0
    created: "2025-04-30T15:58:38.591192+08:00"
    description: A Helm chart for Kubernetes
    digest: 3fd05dc2ba873056c5e2940ed89f757febb7298f6f6ebc4f3a3e45855c7d3290
    name: nexus3
    type: application
    urls:
    - https://huangchengwu.github.io/helm-chart/chart/nexus3-0.1.0.tgz
    version: 0.1.0
  prometheus:
  - apiVersion: v2
    appVersion: 1.16.0
    created: "2025-04-30T15:58:38.591454+08:00"
    description: A Helm chart for Kubernetes
    digest: 2730b60578c3a503f41e021862a2b57c2f7b79a0690592275796dabfc6b3ad68
    name: prometheus
    type: application
    urls:
    - https://huangchengwu.github.io/helm-chart/chart/prometheus-0.1.0.tgz
    version: 0.1.0
  redis:
  - apiVersion: v2
    appVersion: 1.16.0
    created: "2025-04-30T15:58:38.591647+08:00"
    description: A Helm chart for Kubernetes
    digest: 84b52d21da6d99dd59c2677e5961e0fa888067ff41d7f0371340c458fdc6e1cb
    name: redis
    type: application
    urls:
    - https://huangchengwu.github.io/helm-chart/chart/redis-0.1.0.tgz
    version: 0.1.0
  skywalking-v1:
  - apiVersion: v2
    appVersion: 1.16.0
    created: "2025-04-30T15:58:38.591837+08:00"
    description: A Helm chart for Kubernetes
    digest: 0fcdc6f10ae9bbd7bb4cf8747d785461efc6889305716e2d186944b6ff418835
    name: skywalking-v1
    type: application
    urls:
    - https://huangchengwu.github.io/helm-chart/chart/skywalking-v1-0.1.0.tgz
    version: 0.1.0
  tdengine:
  - apiVersion: v2
    appVersion: 3.0.2.2
    created: "2025-04-30T15:58:38.592454+08:00"
    description: TDengine Cluster Chart for Kubenetes
    digest: b1d07640f0b49dbc6c2d35039c18cf03becdc7b75348fd31d7f1618e4448b9f9
    icon: https://www.taosdata.com/images/taosdata-logo.png
    maintainers:
    - email: linhe.huo@gmail.com
      name: Huo Linhe
      url: https://github.com/zitsen
    name: tdengine
    type: application
    urls:
    - https://huangchengwu.github.io/helm-chart/chart/tdengine-3.0.2.tgz
    version: 3.0.2
generated: "2025-04-30T15:58:38.580574+08:00"
