apiVersion: v1
entries:
  cac-system:
  - apiVersion: v2
    appVersion: 1.16.0
    created: "2025-04-30T16:44:05.993471+08:00"
    dependencies:
    - name: metallb
      repository: https://metallb.github.io/metallb
      version: 0.13.10
    - alias: cert-manager
      condition: cert-manager.enabled
      name: cert-manager
      repository: https://charts.jetstack.io
      version: v1.12.0
    description: A Helm chart for Kubernetes
    digest: f5a8f3f892afd5d444f0f9104b9e48a90d735420a04a9bbcc601d3b1121e4624
    name: cac-system
    type: application
    urls:
    - https://huangchengwu.github.io/helm-chart/chart/cac-system-0.1.0.tgz
    version: 0.1.0
  influxdb:
  - apiVersion: v2
    appVersion: 1.16.0
    created: "2025-04-30T16:44:05.993676+08:00"
    description: A Helm chart for Kubernetes
    digest: 3e97cbe4179235fe23adcc8cdffbcc3a319285fed39a468d4bcac63472a8dbd3
    name: influxdb
    type: application
    urls:
    - https://huangchengwu.github.io/helm-chart/chart/influxdb-0.1.0.tgz
    version: 0.1.0
  jenkins:
  - apiVersion: v2
    appVersion: 1.16.0
    created: "2025-04-30T16:44:05.99386+08:00"
    description: A Helm chart for Kubernetes
    digest: c99e437df4afadd4e1bcc63b405fff43dc3d882ddacbf48da7505c125f2bea04
    name: jenkins
    type: application
    urls:
    - https://huangchengwu.github.io/helm-chart/chart/jenkins-0.1.0.tgz
    version: 0.1.0
  mariadb:
  - apiVersion: v2
    appVersion: 1.16.0
    created: "2025-04-30T16:44:05.994058+08:00"
    description: A Helm chart for Kubernetes
    digest: 6c3b7d57f6c1072baf6a180eaa0ad45aad37bcb33515f8cc5b7dedddfb186240
    name: mariadb
    type: application
    urls:
    - https://huangchengwu.github.io/helm-chart/chart/mariadb-0.1.0.tgz
    version: 0.1.0
  mariadb-galera:
  - annotations:
      category: Database
      images: |
        - name: mariadb-galera
          image: docker.io/bitnami/mariadb-galera:11.3.2-debian-12-r3
        - name: mysqld-exporter
          image: docker.io/bitnami/mysqld-exporter:0.15.1-debian-12-r16
      licenses: Apache-2.0
    apiVersion: v2
    appVersion: 11.3.2
    created: "2025-04-30T16:44:05.997304+08:00"
    dependencies:
    - name: common
      repository: oci://registry-1.docker.io/bitnamicharts
      tags:
      - bitnami-common
      version: 2.x.x
    description: MariaDB Galera is a multi-primary database cluster solution for synchronous
      replication and high availability.
    digest: 310389ee00d1da59a809b0e8a9cf565263563c97308aa355956b336cc0bed1e3
    home: https://bitnami.com
    icon: https://bitnami.com/assets/stacks/mariadb-galera/img/mariadb-galera-stack-220x234.png
    keywords:
    - mariadb
    - mysql
    - database
    - sql
    - prometheus
    - galera
    maintainers:
    - name: Broadcom, Inc. All Rights Reserved.
      url: https://github.com/bitnami/charts
    name: mariadb-galera
    sources:
    - https://github.com/bitnami/charts/tree/main/bitnami/mariadb-galera
    urls:
    - https://huangchengwu.github.io/helm-chart/chart/mariadb-galera-13.2.1.tgz
    version: 13.2.1
  mysql:
  - apiVersion: v2
    appVersion: 1.16.0
    created: "2025-04-30T16:44:05.997518+08:00"
    description: A Helm chart for Kubernetes
    digest: 1a8663b1968c98687a5a4986cd6cb47d6ddeb9341552a77803970dac0a342399
    name: mysql
    type: application
    urls:
    - https://huangchengwu.github.io/helm-chart/chart/mysql-0.1.0.tgz
    version: 0.1.0
  nexus3:
  - apiVersion: v2
    appVersion: 1.16.0
    created: "2025-04-30T16:44:05.997682+08:00"
    description: A Helm chart for Kubernetes
    digest: 6b7bb2a06340fe0c1dfffffcb2a31f36fd93b7e36b874f49cff6bf447445165e
    name: nexus3
    type: application
    urls:
    - https://huangchengwu.github.io/helm-chart/chart/nexus3-0.1.0.tgz
    version: 0.1.0
  prometheus:
  - apiVersion: v2
    appVersion: 1.16.0
    created: "2025-04-30T16:44:05.997864+08:00"
    description: A Helm chart for Kubernetes
    digest: 895d668fd6bb29a395361c19621fb4cccb97ca0ce1c2d8cbe8a764c3600bdc1f
    name: prometheus
    type: application
    urls:
    - https://huangchengwu.github.io/helm-chart/chart/prometheus-0.1.0.tgz
    version: 0.1.0
  redis:
  - apiVersion: v2
    appVersion: 1.16.0
    created: "2025-04-30T16:44:05.998038+08:00"
    description: A Helm chart for Kubernetes
    digest: a369fc308e49b776fe64a1912b9356e0b5bafc193b0ec3e4be7d8261fd84881c
    name: redis
    type: application
    urls:
    - https://huangchengwu.github.io/helm-chart/chart/redis-0.1.0.tgz
    version: 0.1.0
  skywalking-v1:
  - apiVersion: v2
    appVersion: 1.16.0
    created: "2025-04-30T16:44:05.998219+08:00"
    description: A Helm chart for Kubernetes
    digest: 94e937c39e3b715596933229006197d9d70e6758539746811220fcad5f001530
    name: skywalking-v1
    type: application
    urls:
    - https://huangchengwu.github.io/helm-chart/chart/skywalking-v1-0.1.0.tgz
    version: 0.1.0
  tdengine:
  - apiVersion: v2
    appVersion: 3.0.2.2
    created: "2025-04-30T16:44:05.998808+08:00"
    description: TDengine Cluster Chart for Kubenetes
    digest: 0fbb9e9011be9e9e0071b0d2775611c6e3fbe1fd9f490c45b6506a2f3fa01bd7
    icon: https://www.taosdata.com/images/taosdata-logo.png
    maintainers:
    - email: linhe.huo@gmail.com
      name: Huo Linhe
      url: https://github.com/zitsen
    name: tdengine
    type: application
    urls:
    - https://huangchengwu.github.io/helm-chart/chart/tdengine-3.0.2.tgz
    version: 3.0.2
generated: "2025-04-30T16:44:05.988239+08:00"
