apiVersion: v1
entries:
  cac-system:
  - apiVersion: v2
    appVersion: 1.16.0
    created: "2023-09-25T11:50:28.195024+08:00"
    dependencies:
    - name: metallb
      repository: https://metallb.github.io/metallb
      version: 0.13.10
    - alias: cert-manager
      condition: cert-manager.enabled
      name: cert-manager
      repository: https://charts.jetstack.io
      version: v1.12.0
    description: A Helm chart for Kubernetes
    digest: 0b7c9d2bafed3064425536bbc38268b2eac00e1180efa07a921fe906f1324942
    name: cac-system
    type: application
    urls:
    - https://huangchengwu.github.io/helm-chart/chart/cac-system-0.1.0.tgz
    version: 0.1.0
  jenkins:
  - apiVersion: v2
    appVersion: 1.16.0
    created: "2023-09-25T11:50:28.195289+08:00"
    description: A Helm chart for Kubernetes
    digest: d96cec31401a81e561fdf7f049862900264388a8e60f8f1726e37fc83646c64d
    name: jenkins
    type: application
    urls:
    - https://huangchengwu.github.io/helm-chart/chart/jenkins-0.1.0.tgz
    version: 0.1.0
  mariadb:
  - apiVersion: v2
    appVersion: 1.16.0
    created: "2023-09-25T11:50:28.195518+08:00"
    description: A Helm chart for Kubernetes
    digest: 4485a3bef1d2c811a81fb82562685fc074cdcdb20ca810fcc6fb3984b53b740f
    name: mariadb
    type: application
    urls:
    - https://huangchengwu.github.io/helm-chart/chart/mariadb-0.1.0.tgz
    version: 0.1.0
  mysql:
  - apiVersion: v2
    appVersion: 1.16.0
    created: "2023-09-25T11:50:28.197978+08:00"
    description: A Helm chart for Kubernetes
    digest: d372b47001acad8daf4a81c770b6efa29f131991d4959aac5c5b51cdf2bb5d0e
    name: mysql
    type: application
    urls:
    - https://huangchengwu.github.io/helm-chart/chart/mysql-0.1.0.tgz
    version: 0.1.0
  nexus3:
  - apiVersion: v2
    appVersion: 1.16.0
    created: "2023-09-25T11:50:28.198179+08:00"
    description: A Helm chart for Kubernetes
    digest: c65c520bf9119e215ee1ed86debcd7c4646ab9e731f69b79849f4392e246d202
    name: nexus3
    type: application
    urls:
    - https://huangchengwu.github.io/helm-chart/chart/nexus3-0.1.0.tgz
    version: 0.1.0
  prometheus:
  - apiVersion: v2
    appVersion: 1.16.0
    created: "2023-09-25T11:50:28.198367+08:00"
    description: A Helm chart for Kubernetes
    digest: c9c654aec1bb952267c94f19c08f6a98567ddf28a7bc0f3cb698a2aefba899d3
    name: prometheus
    type: application
    urls:
    - https://huangchengwu.github.io/helm-chart/chart/prometheus-0.1.0.tgz
    version: 0.1.0
  redis:
  - apiVersion: v2
    appVersion: 1.16.0
    created: "2023-09-25T11:50:28.206878+08:00"
    description: A Helm chart for Kubernetes
    digest: 35e88ccb5922decdb25932bcd6b86432782de3981e367a66b816d39005b426bd
    name: redis
    type: application
    urls:
    - https://huangchengwu.github.io/helm-chart/chart/redis-0.1.0.tgz
    version: 0.1.0
generated: "2023-09-25T11:50:28.188979+08:00"
