apiVersion: v1
kind: Service
metadata:
  name: aria2-pro-svc
  namespace: {{ .Release.Namespace }}
spec:
  selector:
    app: aria2-pro
  ports:
    - protocol: TCP
      port: 6800
      targetPort: 6800

  type: NodePort
