apiVersion: v1
kind: Service
metadata:
  name: oap
  namespace: {{ .Release.Namespace }}

spec:
  ports:
    - name: tcp-12800
      protocol: TCP
      port: 12800
      targetPort: 12800
      nodePort: 32666
    - name: tcp-11800
      protocol: TCP
      port: 11800
      targetPort: 11800
      nodePort: 32667
  selector:
    app: oap
  type: NodePort
---
apiVersion: v1
kind: Service
metadata:
  name: elasticsearch
  namespace: {{ .Release.Namespace }}

spec:
  ports:
    - protocol: TCP
      port: 9200
      targetPort: 9200
  selector:
    app: elasticsearch
  type: ClusterIP

---
apiVersion: v1
kind: Service
metadata:
  name: oap-ui
  namespace: {{ .Release.Namespace }}

spec:
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
      nodePort: 32321

  selector:
    app: oap-ui
  type: NodePort

