apiVersion: v1
kind: Service
metadata:
  name: nexus3-svc
  namespace: {{ .Release.Namespace }}
spec:
  selector:
    app: nexus3
  ports:
    - protocol: TCP
      name: nexus-8081
      port: 8081
      targetPort: 8081
    - protocol: TCP
      port: 8001
      name: nexus-8001

      targetPort: 8001
    - protocol: TCP
      port: 8002
      name: nexus-8002

      targetPort: 8002
    - protocol: TCP
      port: 8003
      name: nexus-8003
      targetPort: 8003
  type: NodePort