apiVersion: v1
kind: Service
metadata:
  name: pinpoint-svc
  namespace: {{ .Release.Namespace }}
spec:
  selector:
    app: pinpoint
  ports:
    - protocol: TCP
      name: pinpoint-80
      port: 80
      targetPort: 80
  type: NodePort
