apiVersion: v1
kind: Service
metadata:
  name: prometheus-svc
  namespace: {{ .Release.Namespace }}
spec:
  selector:
    app: prometheus
  ports:
    - protocol: TCP
      name: prometheus-80
      port: 80
      targetPort: 80
  type: NodePort
