apiVersion: v1
kind: Service
metadata:
  name: pushgateway-api
  namespace: {{ .Release.Namespace }}
spec:
  ports:
    - protocol: TCP
      port: 9091
      targetPort: 9091
  selector:
    app: pushgateway
  type: ClusterIP
---
apiVersion: v1
kind: Service
metadata:
  name: pushgateway
  namespace: {{ .Release.Namespace }}
spec:
  ports:
    - protocol: TCP
      port: 9091
      targetPort: 9091
  selector:
    app: pushgateway
  type: ClusterIP
  clusterIP: None
---
apiVersion: v1
kind: Service
metadata:
  name: prometheus-web
  namespace: {{ .Release.Namespace }}

spec:
  ports:
    - protocol: TCP
      port: 80
      targetPort: 9090
  selector:
    app: prometheus
  type: ClusterIP

---
apiVersion: v1
kind: Service
metadata:
  name: prometheus
  namespace: {{ .Release.Namespace }}
spec:
  ports:
    - protocol: TCP
      port: 9090
      targetPort: 9090
  selector:
    app: prometheus
  clusterIP: None
  type: ClusterIP

