apiVersion: apps/v1
kind: Deployment
metadata:
  name:  cmdb
  labels:
    app: cmdb
spec:
  replicas: 1
  selector:
    matchLabels:
      app: cmdb
  template:
    metadata:
      labels:
        app: cmdb
    spec:
      containers:
        - name: nginx
          image: nginx:1.14.2
          ports:
            - containerPort: 80
