apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mysql-pvc
  namespace: {{ .Release.Namespace }}
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage:  {{ .Values.mysql.storage }}  
  storageClassName:  {{ .Values.storageClassName }} 
  volumeMode: Filesystem