apiVersion: v1
kind: Service
metadata:
  name: mysql-svc
  namespace: {{ .Release.Namespace }}
spec:
  ports:
    - name: mysql
      protocol: TCP
      port: 3306
      targetPort: 3306
  selector:
    app: mysql


