apiVersion: v2
appVersion: 1.16.0
dependencies:
- name: metallb
  repository: https://metallb.github.io/metallb
  version: 0.13.10
- alias: cert-manager
  condition: cert-manager.enabled
  name: cert-manager
  repository: https://charts.jetstack.io
  version: v1.12.0
description: A Helm chart for Kubernetes
name: prometheus
type: application
version: 0.1.0
