apiVersion: v1
kind: Service
metadata:
  name: nexus3-svc
  namespace: {{ .Release.Namespace }}
spec:
  selector:
    app: jenkins
  ports:
    - protocol: TCP
      name: nexus-8081
      port: 8080
      targetPort: 8080
  type: NodePort