apiVersion: v1
kind: Service
metadata:
  name: rsync-svc
  namespace: {{ .Release.Namespace }}
spec:
  selector:
    app: rsync
  ports:
    - protocol: TCP
      name: rsync-80
      port: 80
      targetPort: 80
  type: NodePort
