echo -- >> deploy.yaml && kubectl get namespace/cac-system -n  cac-system  -o yaml >> deploy.yaml
echo -- >> deploy.yaml && kubectl get customresourcedefinition.apiextensions.k8s.io/cacroutes.cac.keli.vip -n  cac-system  -o yaml >> deploy.yaml
echo -- >> deploy.yaml && kubectl get serviceaccount/cac-controller-manager -n  cac-system  -o yaml >> deploy.yaml
echo -- >> deploy.yaml && kubectl get role.rbac.authorization.k8s.io/cac-leader-election-role -n  cac-system  -o yaml >> deploy.yaml
echo -- >> deploy.yaml && kubectl get clusterrole.rbac.authorization.k8s.io/cac-manager-role -n  cac-system  -o yaml >> deploy.yaml
echo -- >> deploy.yaml && kubectl get clusterrole.rbac.authorization.k8s.io/cac-metrics-reader -n  cac-system  -o yaml >> deploy.yaml
echo -- >> deploy.yaml && kubectl get clusterrole.rbac.authorization.k8s.io/cac-proxy-role -n  cac-system  -o yaml >> deploy.yaml
echo -- >> deploy.yaml && kubectl get rolebinding.rbac.authorization.k8s.io/cac-leader-election-rolebinding -n  cac-system  -o yaml >> deploy.yaml
echo -- >> deploy.yaml && kubectl get clusterrolebinding.rbac.authorization.k8s.io/cac-manager-rolebinding -n  cac-system  -o yaml >> deploy.yaml
echo -- >> deploy.yaml && kubectl get clusterrolebinding.rbac.authorization.k8s.io/cac-proxy-rolebinding -n  cac-system  -o yaml >> deploy.yaml
echo -- >> deploy.yaml && kubectl get service/cac-controller-manager-metrics-service -n  cac-system  -o yaml >> deploy.yaml
echo -- >> deploy.yaml && kubectl get service/cac-service -n  cac-system  -o yaml >> deploy.yaml
echo -- >> deploy.yaml && kubectl get service/cac-webhook-service -n  cac-system  -o yaml >> deploy.yaml
echo -- >> deploy.yaml && kubectl get deployment.apps/cac-controller-manager -n  cac-system  -o yaml >> deploy.yaml
echo -- >> deploy.yaml && kubectl get certificate.cert-manager.io/cac-serving-cert -n  cac-system  -o yaml >> deploy.yaml
echo -- >> deploy.yaml && kubectl get issuer.cert-manager.io/cac-selfsigned-issuer -n  cac-system  -o yaml >> deploy.yaml
echo -- >> deploy.yaml && kubectl get mutatingwebhookconfiguration.admissionregistration.k8s.io/cac-mutating-webhook-configuration -n  cac-system  -o yaml >> deploy.yaml
echo -- >> deploy.yaml && kubectl get validatingwebhookconfiguration.admissionregistration.k8s.io/cac-validating-webhook-configuration -n  cac-system  -o yaml >> deploy.yaml
