apiVersion: v1
kind: Service
metadata:
  name: influxdb-svc
  namespace: {{ .Release.Namespace }}
spec:
  ports:
    - name: influxdb
      protocol: TCP
      port: 8086
      targetPort: 8086
  selector:
    app: influxdb
  type: NodePort


---
apiVersion: v1
kind: Service
metadata:
  name: influxdb-headless
  namespace: {{ .Release.Namespace }}
 
spec:
  clusterIP: None
  selector:
    app: influxdb
  ports:
    - protocol: TCP
      port: 8086




