apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: cac-system-pvc
  namespace: {{ .Release.Namespace }}
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage:  {{ .Values.storageSite }}  
  storageClassName:  {{ .Values.storageClassName }} 
  volumeMode: Filesystem
