apiVersion: v1
kind: Service
metadata:
  name: mariadb-svc
  namespace: {{ .Release.Namespace }}

spec:
  ports:
    - name: mariadb
      protocol: TCP
      port: 3306
      targetPort: 3306
  selector:
    app: mariadb
  type: NodePort


