apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mariadb-pvc
  namespace: {{ .Release.Namespace }}

spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage:  {{ .Values.storageSite }}  
  storageClassName:  {{ .Values.storageClassName }} 
  volumeMode: Filesystem