apiVersion: apps/v1
kind: Deployment
metadata:
  name: mariadb
  namespace: {{ .Release.Namespace }}

spec:
  replicas: 1
  selector:
    matchLabels:
      app: mariadb
  template:
    metadata:
      labels:
        app: mariadb
    spec:
      volumes:
        - name: mariadb-persistent-storage
          persistentVolumeClaim:
            claimName: mariadb-pvc
        - name: mariadb-conf
          configMap:
            name: mariadb-conf
            items:
              - key: 50-server.cnf
                path: 50-server.cnf
            defaultMode: 420

      containers:
        - name: mariadb
          image: {{ .Values.image }}
          ports:
            - containerPort: 3306
              protocol: TCP
          env:
            - name: MYSQL_ROOT_PASSWORD
              value: {{ .Values.password }}
            - name: MYSQL_DATABASE
              value: {{ .Values.database }}
            - name: MYSQL_USER
              value: {{ .Values.user }}
            - name: MYSQL_PASSWORD
              value: {{ .Values.password }}
              
          volumeMounts:
            - name: mariadb-persistent-storage
              mountPath: /var/lib/mysql
            - name: mariadb-conf
              mountPath: /etc/mysql/mariadb.conf.d/50-server.cnf
              subPath: 50-server.cnf
              
          imagePullPolicy: Always
      restartPolicy: Always
