apiVersion: v1
kind: ConfigMap
metadata:
  name: filebeat-config
  namespace: {{ .Release.Namespace }}
data:
  filebeat.yml: |
    setup.template.name: "my-custom-template"
    setup.template.pattern: "my-custom-index-*"
    filebeat.inputs:
    - type: log
      enabled: true
      paths:
        - /var/log/containers/*.log
    output.elasticsearch:
      hosts: ["elasticsearch:9200"]
      index: "my-custom-index-%{+yyyy.MM.dd}"


---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: kibana
  namespace: {{ .Release.Namespace }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kibana
  template:
    metadata:
      labels:
        app: kibana
    spec:
      containers:
        - name: kibana
          image: kibana:7.17.13
          ports:
            - containerPort: 5601      
          env:
          - name: ELASTICSEARCH_HOSTS
            value: http://elasticsearch:9200
---
apiVersion: apps/v1
kind: DaemonSet
metadata:
  name:  filebeat
  namespace: {{ .Release.Namespace }}
  labels:
    k8s-app: filebeat
spec:
  selector:
    matchLabels:
      name: filebeat
  template:
    metadata:
      labels:
        name: filebeat
    spec:
      hostNetwork: true  
      containers:
      - name: filebeat
        image: elastic/filebeat:7.17.13
        command: ["filebeat", "-e","-v","-c","/filebeat/filebeat.yml"]
        securityContext:
          runAsUser: 0
        volumeMounts:
        - name: varlogcontainers
          mountPath: /var/log/containers
        - name: varlogcontainers2
          mountPath: /var/log/pods



        - name: config-volume
          mountPath: /filebeat/filebeat.yml
          subPath: filebeat.yml
          readOnly: true
      volumes:
      - name: varlogcontainers
        hostPath:
          path: /var/log/containers
          type: ""
      - name: varlogcontainers2
        hostPath:
          path: /var/log/pods
          type: ""

      - name: config-volume
        configMap:
          name: filebeat-config 
          items:
            - key: filebeat.yml
              path: filebeat.yml
          defaultMode: 420
