apiVersion: v1
kind: Service
metadata:
  name: elasticsearch
  namespace: {{ .Release.Namespace }}
spec:
  selector:
    app: elasticsearch
  ports:
    - protocol: TCP
      name: elasticsearch-9200
      port: 9200
      targetPort: 9200
    - protocol: TCP
      name: elasticsearch-5601
      port: 5601
      targetPort: 5601
    - protocol: TCP
      name: elasticsearch-9300
      port: 9300
      targetPort: 9300
  type: NodePort
